name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "Prefix for the repository name"
        required: true
        default: "service"
        type: choice
        options:
          - exmaple
          - service
      name:
        description: "set repo name"
        required: true
        default: "github-actions"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create repo
        run: |
          gh repo create june-github-action-practice/${{ inputs.prefix }}-${{ inputs.name }} --public  --add-readme

  send-slack-message:
    needs: [create-repo-automation]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
