name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "Prefix for the repository name"
        required: true
        default: "service"
        type: choice
        options:
          - exmaple
          - service
      name:
        description: "set repo name"
        required: true
        default: "github-actions"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKE }} | gh auth login --with-token
      - name: create repo
        run: |
          gh repo create june-github-action-practice/${{ inputs.prefix }}-${{ inputs.name }} --public  --add-readme
